
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public TbItem TbItem {get; }
    public TbNewItem TbNewItem {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new TbItem(loader("tbitem"));
        TbNewItem = new TbNewItem(loader("tbnewitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbNewItem.ResolveRef(this);
    }
}

}
