
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbNewItem
{
    private readonly System.Collections.Generic.Dictionary<int, NewItem> _dataMap;
    private readonly System.Collections.Generic.List<NewItem> _dataList;
    
    public TbNewItem(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, NewItem>(n);
        _dataList = new System.Collections.Generic.List<NewItem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            NewItem _v;
            _v = global::cfg.NewItem.DeserializeNewItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, NewItem> DataMap => _dataMap;
    public System.Collections.Generic.List<NewItem> DataList => _dataList;

    public NewItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public NewItem Get(int key) => _dataMap[key];
    public NewItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

